# Generated by Django 3.1.4 on 2020-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intradaydata',
            name='symbol',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
